"""add devices.release_year

Revision ID: 22e54a143ae3
Revises: b310f2cb52f7
Create Date: 2026-08-16 22:47:55.687048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import app.core.crypto


# revision identifiers, used by Alembic.
revision: str = '22e54a143ae3'
down_revision: Union[str, Sequence[str], None] = 'b310f2cb52f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('devices', sa.Column('release_year', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_devices_release_year'), 'devices', ['release_year'], unique=False)

    # Backfill here rather than in a separate script: this runs as part of
    # `alembic upgrade head`, which is already the deploy's start command,
    # so every environment fills itself instead of waiting for someone to
    # remember a one-off. Only touches rows that are still null, so it is
    # safe to re-run and never overwrites a value set by hand later.
    from app.services.release_year import release_year_for

    conn = op.get_bind()
    models = conn.execute(
        sa.text("select distinct model from devices where release_year is null")
    ).scalars().all()

    for model in models:
        year = release_year_for(model)
        if year is None:
            continue
        conn.execute(
            sa.text(
                "update devices set release_year = :year "
                "where model = :model and release_year is null"
            ),
            {"year": year, "model": model},
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_devices_release_year'), table_name='devices')
    op.drop_column('devices', 'release_year')
    # ### end Alembic commands ###
