"""initial schema

Revision ID: ce35cf826132
Revises: 
Create Date: 2026-08-08 10:53:30.517660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import app.core.crypto


# revision identifiers, used by Alembic.
revision: str = 'ce35cf826132'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('brand', sa.Enum('apple', 'samsung', name='brand'), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('storage_gb', sa.Integer(), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('category', sa.Enum('phone', 'tablet', 'watch', name='devicecategory'), nullable=False),
    sa.Column('has_s_pen', sa.Boolean(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_slug'), 'devices', ['slug'], unique=True)
    op.create_table('question_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('phone', 'tablet', 'watch', name='devicecategory'), nullable=False),
    sa.Column('brand', sa.Enum('apple', 'samsung', name='brand'), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address_line', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('postal_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('opening_hours', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('base_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('liquidity_tier', sa.Enum('high', 'medium', 'low', name='liquiditytier'), nullable=False),
    sa.Column('markup_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_base_prices_device_id'), 'base_prices', ['device_id'], unique=True)
    op.create_table('competitor_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('competitor_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('price', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('condition_tier', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitor_prices_device_id'), 'competitor_prices', ['device_id'], unique=False)
    op.create_table('price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_history_device_id'), 'price_history', ['device_id'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_set_id', sa.Integer(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sa.Enum('single_select', 'multi_select', 'boolean', 'device_selector', name='questiontype'), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('depends_on_question_id', sa.Integer(), nullable=True),
    sa.Column('depends_on_value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('requires_device_attribute', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['depends_on_question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['question_set_id'], ['question_sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_question_set_id'), 'questions', ['question_set_id'], unique=False)
    op.create_table('quotes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=True),
    sa.Column('base_price_at_quote', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('calculated_price', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'expired', 'inspected', 'paid', 'manual_review', 'rejected', name='quotestatus'), nullable=False),
    sa.Column('fulfillment_method', sa.Enum('store', 'courier', name='fulfillmentmethod'), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('customer_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('customer_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('customer_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotes_device_id'), 'quotes', ['device_id'], unique=False)
    op.create_table('deduction_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('option_value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('deduction_type', sa.Enum('percentage', 'fixed', name='deductiontype'), nullable=False),
    sa.Column('deduction_value', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('is_disqualifying', sa.Boolean(), nullable=False),
    sa.Column('disqualify_status', sa.Enum('rejected', 'manual_review', name='disqualifystatus'), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deduction_rules_question_id'), 'deduction_rules', ['question_id'], unique=False)
    op.create_table('payouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quote_id', sa.Uuid(), nullable=False),
    sa.Column('iban', app.core.crypto.EncryptedString(), nullable=False),
    sa.Column('account_holder_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('status', sa.Enum('pending', 'paid', name='payoutstatus'), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payouts_quote_id'), 'payouts', ['quote_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payouts_quote_id'), table_name='payouts')
    op.drop_table('payouts')
    op.drop_index(op.f('ix_deduction_rules_question_id'), table_name='deduction_rules')
    op.drop_table('deduction_rules')
    op.drop_index(op.f('ix_quotes_device_id'), table_name='quotes')
    op.drop_table('quotes')
    op.drop_index(op.f('ix_questions_question_set_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_price_history_device_id'), table_name='price_history')
    op.drop_table('price_history')
    op.drop_index(op.f('ix_competitor_prices_device_id'), table_name='competitor_prices')
    op.drop_table('competitor_prices')
    op.drop_index(op.f('ix_base_prices_device_id'), table_name='base_prices')
    op.drop_table('base_prices')
    op.drop_table('stores')
    op.drop_table('question_sets')
    op.drop_index(op.f('ix_devices_slug'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
